version: '3'

services:

  db:
    image: mysql
    container_name: "wobot_ai_db"
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  web:
    build: .
    container_name: wobot_ai_web
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    # environment:
    #   - name=value
    env_file:
      - .env
    depends_on: 
      - db
    volumes: 
      - .:/code